/**
 * Generates lefthook.yml for git hook enforcement:
 * - commit-msg: conventional commits + atomic commit discipline
 * - pre-commit: style check + TDD enforcement
 * - pre-push: mutation tests + semgrep SAST + PR size limit
 */

import type { DevConfig } from '../config.js'

export function generateLefthook(config: DevConfig): string {
  const lint = config.commands.lint
  const typecheck = config.commands.typecheck
  const test = config.commands.test

  return `# lefthook.yml — generated by @oisincoveney/dev
# See https://github.com/evilmartians/lefthook

commit-msg:
  commands:
    conventional-commits:
      run: |
        if ! head -1 {1} | grep -qE '^(feat|fix|chore|refactor|test|docs|style|perf|ci|build|revert)(\\([a-z0-9-]+\\))?!?: .+'; then
          echo "⛔ Commit message must follow Conventional Commits format:"
          echo "   <type>(<scope>): <subject>"
          echo "   Allowed types: feat, fix, chore, refactor, test, docs, style, perf, ci, build, revert"
          exit 1
        fi
    atomic-commits:
      run: |
        subject=$(head -1 {1})
        if echo "$subject" | grep -qE ' and '; then
          echo "⛔ Commit subject contains 'and' — split into atomic commits."
          echo "   Each commit should do one thing. Refactoring and feature work go in separate commits."
          exit 1
        fi
    no-coauthor:
      run: |
        if grep -qi "Co-Authored-By:" {1}; then
          echo "⛔ Co-Authored-By trailers are not allowed in this project."
          exit 1
        fi

pre-commit:
  commands:
    typecheck:
      run: ${typecheck}
    lint:
      run: ${lint}
    tdd-guard:
      run: .claude/hooks/tdd-guard.sh

pre-push:
  commands:
    test:
      run: ${test}
    pr-size-check:
      run: .claude/hooks/pr-size-check.sh
    semgrep:
      run: |
        if command -v semgrep >/dev/null 2>&1; then
          semgrep --config p/security-audit --config p/owasp-top-ten --error
        fi
`
}
