/**
 * Generates lefthook.yml for git hook enforcement:
 * - commit-msg: conventional commits + atomic commit discipline
 * - pre-commit: style check + TDD enforcement
 * - pre-push: mutation tests + semgrep SAST + PR size limit
 */

import type { DevConfig } from '../config.js'

const TS_FRONTEND_VARIANTS = ['ts-frontend', 'ts-fullstack'] as const
type TsFrontendVariant = (typeof TS_FRONTEND_VARIANTS)[number]

function isFrontendVariant(variant: string): variant is TsFrontendVariant {
  return (TS_FRONTEND_VARIANTS as ReadonlyArray<string>).includes(variant)
}

export function generateLefthook(config: DevConfig): string {
  const lint = config.commands.lint
  const typecheck = config.commands.typecheck
  const test = config.commands.test
  const e2e = config.commands.e2e

  const typecheckStep = typecheck
    ? `    typecheck:
      run: ${typecheck}
`
    : ''
  const lintStep = lint
    ? `    lint:
      run: ${lint}
`
    : ''
  const testStep = test
    ? `    test:
      run: ${test}
`
    : ''

  const playwrightStep =
    isFrontendVariant(config.variant) && e2e
      ? `    playwright:
      run: |
        if command -v playwright >/dev/null 2>&1; then
          ${e2e}
        fi
`
      : ''

  const tsStyleGuardStep =
    config.language === 'typescript'
      ? `    ts-style-guard:
      glob: "**/*.{ts,tsx}"
      exclude: "**/components/ui/**"
      run: |
        FAIL=0
        for f in {staged_files}; do
          if grep -nP ':\\s*any\\b|<any\\s*>|as\\s+any\\b' "$f" | grep -vP '^\\s*//' > /dev/null 2>&1; then
            echo "⛔ $f: \`any\` type — use unknown and narrow"
            FAIL=1
          fi
          if grep -nE '^\\s*//\\s*@ts-(ignore|expect-error)' "$f" > /dev/null 2>&1; then
            echo "⛔ $f: @ts-ignore or @ts-expect-error — fix the type error"
            FAIL=1
          fi
          if grep -nP '\\bcreateContext\\s*[<(]' "$f" | grep -vP '^\\s*//' > /dev/null 2>&1; then
            echo "⛔ $f: createContext — use Jotai atoms"
            FAIL=1
          fi
          if grep -nP 'style\\s*=\\s*\\{\\{' "$f" > /dev/null 2>&1; then
            echo "⛔ $f: inline styles — use Tailwind"
            FAIL=1
          fi
          if grep -nP 'className=.*\\[[^\\]]+\\]' "$f" > /dev/null 2>&1; then
            echo "⛔ $f: arbitrary Tailwind values — use theme tokens"
            FAIL=1
          fi
          if grep -nP 'className=.*(bg|text|border|ring)-(red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose|slate|gray|zinc|neutral|stone|white|black)-[0-9]' "$f" > /dev/null 2>&1; then
            echo "⛔ $f: color-specific Tailwind class — use design tokens"
            FAIL=1
          fi
          if grep -nE '^export\\s+default\\b' "$f" > /dev/null 2>&1; then
            echo "⛔ $f: export default — use named exports"
            FAIL=1
          fi
          if grep -nP '\\bconsole\\.log\\s*\\(' "$f" | grep -vP '^\\s*//' > /dev/null 2>&1; then
            echo "⛔ $f: console.log — use structured logging"
            FAIL=1
          fi
          lines=$(wc -l < "$f" | tr -d ' ')
          if [ "$lines" -gt 300 ]; then
            echo "⛔ $f: $lines lines exceeds 300-line limit — split the file"
            FAIL=1
          fi
        done
        if [ $FAIL -ne 0 ]; then
          echo "Fix violations above. See CLAUDE.md for full rules."
          exit 1
        fi
`
      : ''

  return `# lefthook.yml — generated by @oisincoveney/dev
# See https://github.com/evilmartians/lefthook

commit-msg:
  commands:
    conventional-commits:
      run: |
        if ! head -1 {1} | grep -qE '^(feat|fix|chore|refactor|test|docs|style|perf|ci|build|revert)(\\([a-z0-9-]+\\))?!?: .+'; then
          echo "⛔ Commit message must follow Conventional Commits format:"
          echo "   <type>(<scope>): <subject>"
          echo "   Allowed types: feat, fix, chore, refactor, test, docs, style, perf, ci, build, revert"
          exit 1
        fi
    atomic-commits:
      run: |
        subject=$(head -1 {1})
        if echo "$subject" | grep -qE ' and '; then
          echo "⛔ Commit subject contains 'and' — split into atomic commits."
          echo "   Each commit should do one thing. Refactoring and feature work go in separate commits."
          exit 1
        fi
    no-coauthor:
      run: |
        if grep -qi "Co-Authored-By:" {1}; then
          echo "⛔ Co-Authored-By trailers are not allowed in this project."
          exit 1
        fi

pre-commit:
  parallel: true
  commands:
${tsStyleGuardStep}${typecheckStep}${lintStep}    tdd-guard:
      run: .claude/hooks/tdd-guard.sh

pre-push:
  commands:
${testStep}${playwrightStep}    pr-size-check:
      run: .claude/hooks/pr-size-check.sh
    semgrep:
      run: |
        if command -v semgrep >/dev/null 2>&1; then
          semgrep --config p/security-audit --config p/owasp-top-ten --error
        fi
`
}
