/**
 * Generates language-specific lint/format configs.
 * TS: handled by Vite+ (no config generated)
 * Rust: clippy.toml, rustfmt.toml
 * Go: .golangci.yml
 */

import type { DevConfig } from '../config.js'

export function generateLintConfig(config: DevConfig): Record<string, string> {
  switch (config.language) {
    case 'typescript':
      // Vite+ owns TS lint config via vp check
      return {}
    case 'rust':
      return {
        'clippy.toml': rustClippyConfig(),
        'rustfmt.toml': rustFmtConfig(),
      }
    case 'go':
      return {
        '.golangci.yml': goLangciConfig(),
      }
  }
}

function rustClippyConfig(): string {
  return `# clippy.toml — generated by @oisincoveney/dev
cognitive-complexity-threshold = 25
too-many-arguments-threshold = 4
type-complexity-threshold = 250
disallowed-names = [
  "data",
  "info",
  "item",
  "handler",
  "manager",
  "util",
  "helper",
  "tmp",
  "foo",
  "bar",
  "baz",
]
allow-unwrap-in-tests = true
allow-expect-in-tests = true
avoid-breaking-exported-api = false
`
}

function rustFmtConfig(): string {
  return `# rustfmt.toml — generated by @oisincoveney/dev
edition = "2024"
max_width = 100
use_small_heuristics = "Max"
newline_style = "Unix"
format_code_in_doc_comments = true
normalize_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
`
}

function goLangciConfig(): string {
  return `# .golangci.yml — generated by @oisincoveney/dev
version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - exhaustive
    - wrapcheck
    - gocyclo
    - gocognit
    - cyclop
    - funlen
    - unused
    - ineffassign
    - unparam
    - varnamelen
    - revive
    - dupl
    - gocritic
    - depguard
    - forbidigo
    - godox
    - gofumpt
    - gosec
    - govet
    - staticcheck
    - bodyclose
    - noctx
settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  cyclop:
    max-complexity: 15
  funlen:
    lines: 60
    statements: 40
    ignore-comments: true
  varnamelen:
    min-name-length: 3
    ignore-names: [i, j, k, id, ok, tx, db, ws, ip, tc]
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
  dupl:
    threshold: 100
  forbidigo:
    forbid:
      - pattern: '^TODO($|[^(])'
        msg: "TODOs must include (owner, YYYY-MM-DD)"
      - pattern: '^FIXME($|[^(])'
        msg: "FIXMEs must include (owner, YYYY-MM-DD)"
      - pattern: 'fmt\\.Println'
        msg: "Use structured logging (slog) instead of fmt.Println"
  revive:
    rules:
      - name: var-naming
      - name: error-return
      - name: error-naming
      - name: exported
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
`
}
