/**
 * Generates .opencode/plugins/dev-enforcer.ts.
 *
 * OpenCode subscribes to `tool.execute.before` events. The plugin enforces
 * the same rules as the Claude/Codex hooks — destructive commands, fabricated
 * imports, TodoWrite→beads — by shelling out to the shared bash scripts.
 */

import type { DevConfig } from '../config.js'

export function generateOpencodePlugin(_config: DevConfig): string {
  return `// dev-enforcer.ts — generated by @oisincoveney/dev
// Intercepts opencode tool.execute.before events and enforces the same rules
// as the Claude Code hooks by running the shared bash hooks.

import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

interface ToolEvent {
  tool: string
  input: Record<string, unknown>
}

const HOOKS_DIR = '.claude/hooks'

function runHook(name: string, input: unknown): { allowed: boolean; message?: string } {
  const path = join(HOOKS_DIR, name)
  if (!existsSync(path)) return { allowed: true }

  const result = spawnSync(path, [], {
    input: JSON.stringify(input),
    encoding: 'utf8',
    timeout: 30_000,
  })

  if (result.status === 2) {
    return { allowed: false, message: result.stderr || 'Blocked by hook' }
  }
  return { allowed: true }
}

export default {
  name: 'dev-enforcer',
  async 'tool.execute.before'(event: ToolEvent): Promise<void> {
    const toolInput = { tool_input: event.input }

    // Destructive bash commands
    if (event.tool === 'bash') {
      const destructive = runHook('destructive-command-guard.sh', toolInput)
      if (!destructive.allowed) {
        throw new Error(destructive.message)
      }
      const coauthor = runHook('block-coauthor.sh', toolInput)
      if (!coauthor.allowed) {
        throw new Error(coauthor.message)
      }
      return
    }

    // Fabricated imports and anti-patterns on write/edit
    if (['write', 'edit', 'multiedit', 'patch'].includes(event.tool)) {
      const imports = runHook('import-validator.sh', toolInput)
      if (!imports.allowed) {
        throw new Error(imports.message)
      }
      const antipattern = runHook('ai-antipattern-guard.sh', toolInput)
      if (!antipattern.allowed) {
        throw new Error(antipattern.message)
      }
      return
    }

    // Block todo writes
    if (event.tool === 'todowrite' || event.tool === 'todo_write') {
      const block = runHook('block-todowrite.sh', toolInput)
      if (!block.allowed) {
        throw new Error(block.message)
      }
    }
  },
}
`
}
