/**
 * Generates tool config files: .semgrep.yml, commitlint.config.cjs,
 * stryker.conf.json / cargo-mutants / go-mutesting, .dependency-cruiser.cjs,
 * strict tsconfig override.
 */

import type { DevConfig } from '../config.js'

export function generateToolConfigs(config: DevConfig): Record<string, string> {
  const out: Record<string, string> = {
    '.semgrep.yml': semgrepConfig(),
    'commitlint.config.cjs': commitlintConfig(),
  }

  switch (config.language) {
    case 'typescript':
      out['stryker.conf.json'] = strykerConfig(config)
      if (config.contractDriven) {
        out['.dependency-cruiser.cjs'] = dependencyCruiserConfig()
      }
      out['tsconfig.strict.json'] = strictTsconfig()
      break
    case 'rust':
      out['.cargo-mutants.toml'] = cargoMutantsConfig()
      break
    case 'go':
      out['.go-mutesting.yml'] = goMutestingConfig()
      break
  }

  return out
}

function semgrepConfig(): string {
  return `# .semgrep.yml — generated by @oisincoveney/dev
# Run via: semgrep --config .semgrep.yml
rules: []
# We use community rulesets via the Semgrep registry:
# semgrep --config p/security-audit --config p/owasp-top-ten --config p/cwe-top-25
`
}

function commitlintConfig(): string {
  return `// commitlint.config.cjs — generated by @oisincoveney/dev
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'chore', 'refactor', 'test', 'docs', 'style', 'perf', 'ci', 'build', 'revert'],
    ],
    'subject-empty': [2, 'never'],
    'subject-case': [0],
    'header-max-length': [2, 'always', 100],
  },
}
`
}

function strykerConfig(config: DevConfig): string {
  const testRunner = config.framework === 'vitest' || config.variant.startsWith('ts-') ? 'vitest' : 'jest'
  return `{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "${config.packageManager}",
  "reporters": ["progress", "clear-text", "html"],
  "testRunner": "${testRunner}",
  "coverageAnalysis": "perTest",
  "mutate": [
    "src/**/*.ts",
    "!src/**/*.test.ts",
    "!src/**/*.spec.ts",
    "!src/**/__tests__/**"
  ],
  "thresholds": { "high": 85, "low": 70, "break": 60 }
}
`
}

function dependencyCruiserConfig(): string {
  return `// .dependency-cruiser.cjs — enforces contract-driven module boundaries.
// Other modules may only import from a module's index.ts, never internals.
module.exports = {
  forbidden: [
    {
      name: 'no-module-internal-imports',
      severity: 'error',
      comment:
        'Modules may only be imported via their public interface (index.ts). ' +
        'Importing internal files breaks the contract.',
      from: { path: '^src/modules/([^/]+)/' },
      to: {
        path: '^src/modules/([^/]+)/(?!index\\\\.ts$).+',
        pathNot: '^src/modules/$1/',
      },
    },
    {
      name: 'no-circular',
      severity: 'error',
      comment: 'Circular dependencies.',
      from: {},
      to: { circular: true },
    },
    {
      name: 'no-orphans',
      severity: 'warn',
      comment: 'Orphan modules (no one imports them).',
      from: {
        orphan: true,
        pathNot: [
          '(^|/)\\\\.[^/]+\\\\.(js|cjs|mjs|ts|tsx)$',
          '\\\\.d\\\\.ts$',
          '(^|/)tsconfig\\\\.json$',
          '(^|/)(?:package|pnpm-workspace)\\\\.(json|ya?ml)$',
        ],
      },
      to: {},
    },
  ],
  options: {
    doNotFollow: { path: 'node_modules' },
    tsPreCompilationDeps: true,
    tsConfig: { fileName: 'tsconfig.json' },
  },
}
`
}

function strictTsconfig(): string {
  return `{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitAny": true,
    "exactOptionalPropertyTypes": true,
    "useUnknownInCatchVariables": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitOverride": true
  }
}
`
}

function cargoMutantsConfig(): string {
  return `# .cargo-mutants.toml — generated by @oisincoveney/dev
timeout_multiplier = 3.0
minimum_test_timeout = 20.0
exclude_globs = ["tests/**", "benches/**"]
`
}

function goMutestingConfig(): string {
  return `# .go-mutesting.yml — generated by @oisincoveney/dev
mutator:
  disabled:
    - branch/case
timeout: 10
test:
  command: go test ./...
`
}
